name: Generate RSS Feed

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟执行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python generate_rss.py
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B gh-pages
          git add rss.xml
          git commit -m "Update RSS"
          git push -f origin gh-pages

