name: 澳门天气预警RSS自动生成

# 触发条件：每15分钟自动运行 + 允许手动触发
on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:        # 手动触发按钮

jobs:
  generate-rss:
    runs-on: ubuntu-latest  # 使用GitHub提供的云端虚拟机
    
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4  # 最新版checkout工具
      
      - name: 设置Python环境
        uses: actions/setup-python@v5  # 云端配置Python
        with:
          python-version: '3.11'  # 指定Python版本
      
      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install feedgen beautifulsoup4 requests
      
      - name: 运行RSS生成脚本
        run: python generate_rss.py
      
      - name: 部署到gh-pages分支
        uses: peaceiris/actions-gh-pages@v4  # 专业部署工具
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的安全令牌
          publish_dir: ./output  # 只部署output目录
          force_orphan: true  # 保持分支干净
          commit_message: "自动更新天气预警RSS: ${{ github.sha }}"
    